SELECT va.RELEASEID, va.INSTALLATIONID, FORMAT(i.TIMESTAMP AT TIME ZONE 'ENTER_TIME_ZONE', 'ENTER_DATE_FORMAT') AS TIMESTAMP
FROM [ENTER_WINDCHILL_SCHEMA].[WtUpgInst_VersionedAssembly] va
INNER JOIN [ENTER_WINDCHILL_SCHEMA].[WtUpgInst_Installation] i ON i.ID = va.INSTALLATIONID
ORDER BY va.INSTALLATIONID DESC, va.RELEASEID;
