SELECT va.RELEASEID, va.INSTALLATIONID, i.TIMESTAMP
FROM [ENTER_WINDCHILL_SCHEMA].[WtUpgInst_VersionedAssembly] va
INNER JOIN [ENTER_WINDCHILL_SCHEMA].[WtUpgInst_Installation] i ON i.ID = va.INSTALLATIONID
ORDER BY va.INSTALLATIONID DESC, va.RELEASEID;
